// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-DiR7_J-uUlIzBpf3RtCK4HQ7KOj1HXM',
    appId: '1:77454724137:web:cd1dddf5cb055c03692038',
    messagingSenderId: '77454724137',
    projectId: 'yellowtail-6fdd3',
    authDomain: 'yellowtail-6fdd3.firebaseapp.com',
    storageBucket: 'yellowtail-6fdd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP4yHhGmdea5Q_GlAlsuxrW-wLnqEyBTw',
    appId: '1:77454724137:android:fd5dfff97fc33db4692038',
    messagingSenderId: '77454724137',
    projectId: 'yellowtail-6fdd3',
    storageBucket: 'yellowtail-6fdd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ZSdQtDJaxGf_mAO6IFafadXmgEo5gd0',
    appId: '1:77454724137:ios:64a32a79f9cb61aa692038',
    messagingSenderId: '77454724137',
    projectId: 'yellowtail-6fdd3',
    storageBucket: 'yellowtail-6fdd3.firebasestorage.app',
    iosBundleId: 'com.example.cyberProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ZSdQtDJaxGf_mAO6IFafadXmgEo5gd0',
    appId: '1:77454724137:ios:64a32a79f9cb61aa692038',
    messagingSenderId: '77454724137',
    projectId: 'yellowtail-6fdd3',
    storageBucket: 'yellowtail-6fdd3.firebasestorage.app',
    iosBundleId: 'com.example.cyberProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-DiR7_J-uUlIzBpf3RtCK4HQ7KOj1HXM',
    appId: '1:77454724137:web:a40cc5ab768885ce692038',
    messagingSenderId: '77454724137',
    projectId: 'yellowtail-6fdd3',
    authDomain: 'yellowtail-6fdd3.firebaseapp.com',
    storageBucket: 'yellowtail-6fdd3.firebasestorage.app',
  );

}